version: 2
jobs:
   build:
     docker:
       - image: circleci/python:2.7
     steps:
       - run: pip install .
   test:
     docker:
       - image: circleci/python:2.7
     steps:
       - run: docker_installer --local --log info --password
workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test:
          requires:
            - build
          filters:
            branches:
              only: master